update script and defaults

diff --git a/slay b/slay
--- a/slay
+++ b/slay
@@ -13,11 +13,11 @@ set -e
 ###############################################################################
 
 if [ -e twirl ]; then
-	cd "$(dirname "${BASH_SOURCE[0]}")" \
-		&& . "twirl"
+  cd "$(dirname "${BASH_SOURCE[0]}")" \
+  && . "twirl"
 else
-	printf "\n ⚠️  ./twirl not found  💃🏾 First, you need to twirl on your haters\n"
-	exit 1
+  printf "\n ⚠️  ./twirl not found  💃🏾 First, you need to twirl on your haters\n"
+  exit 1
 fi
 
 ###############################################################################
@@ -27,23 +27,23 @@ fi
 check_bash_version
 
 ###############################################################################
-# Get in Formation!          http://patorjk.com/software/taag/ ( font: Script )
+# Get in Formation!      http://patorjk.com/software/taag/ ( font: Script )
 ###############################################################################
 
 printf "
    _
   | |
-  | |  __   ,_    _  _  _    __, _|_ 🍋  __   _  _
+  | |  __   ,_  _  _  _  __, _|_ 🍋  __   _  _
   |/  /  \_/  |  / |/ |/ |  /  |  |  |  /  \_/ |/ |
-  |__/\__/    |_/  |  |  |_/\_/|_/|_/|_/\__/   |  |
+  |__/\__/  |_/  |  |  |_/\_/|_/|_/|_/\__/   |  |
   |\  ---------------------------------------------
-  |/  Cause you slay           [for Bash 3.2 - 3.9]
+  |/  Cause you slay       [for Bash 3.2 - 3.9]
 ╭───────────────────────────────────────────────────╮
-│  Okay developers now let's get in ${bold}formation${normal}.      │
+│  Okay developers now let's get in ${bold}formation${normal}.    │
 │───────────────────────────────────────────────────│
 │  Safe to run multiple times on the same machine.  │
 │  It ${green}installs${reset}, ${blue}upgrades${reset}, or ${yellow}skips${reset} packages based   │
-│  on what is already installed on the machine.     │
+│  on what is already installed on the machine.   │
 ╰───────────────────────────────────────────────────╯
    ${dim}$(get_os) $(get_os_version) ${normal} // ${dim}$BASH ${normal} // ${dim}$BASH_VERSION${reset}
 "
@@ -75,74 +75,62 @@ chapter "Installing Dependencies…"
 # XCode
 # -----------------------------------------------------------------------------
 if type xcode-select >&- && xpath=$( xcode-select --print-path ) &&
-	test -d "${xpath}" && test -x "${xpath}" ; then
-	print_success_muted "Xcode already installed. Skipping."
+  test -d "${xpath}" && test -x "${xpath}" ; then
+  print_success_muted "Xcode already installed. Skipping."
 else
-	step "Installing Xcode…"
-	xcode-select --install
-	print_success "Xcode installed!"
+  step "Installing Xcode…"
+  xcode-select --install
+  print_success "Xcode installed!"
 fi
 
 if [ ! -d "$HOME/.bin/" ]; then
-	mkdir "$HOME/.bin"
-fi
-
-# -----------------------------------------------------------------------------
-# Bash-it
-# -----------------------------------------------------------------------------
-if [ -d "$HOME/.bash_it" ]; then
-	print_success_muted "Bash-it already installed. Skipping."
-else
-	step "Installing Bash-it…"
-	git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
-	~/.bash_it/install.sh --silent --no-modify-config
-	print_success "Bash-it installed!"
+  mkdir "$HOME/.bin"
 fi
 
 # -----------------------------------------------------------------------------
 # NVM
 # -----------------------------------------------------------------------------
 if [ -x nvm ]; then
-	step "Installing NVM…"
-	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
-	print_success "NVM installed!"
-	step "Installing latest Node…"
-	nvm install node
-	nvm use node
-	nvm run node --version
-	nodev=$(node -v)
-	print_success "Using Node $nodev!"
+  step "Installing NVM…"
+  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
+  print_success "NVM installed!"
+  step "Installing latest Node…"
+  nvm install node
+  nvm use node
+  nvm run node --version
+  nodev=$(node -v)
+  print_success "Using Node $nodev!"
 else
-	print_success_muted "NVM/Node already installed. Skipping."
+  print_success_muted "NVM/Node already installed. Skipping."
 fi
 
 # -----------------------------------------------------------------------------
 # Homebrew
 # -----------------------------------------------------------------------------
 if ! [ -x "$(command -v brew)" ]; then
-	step "Installing Homebrew…"
-	curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
-	export PATH="/usr/local/bin:$PATH"
-	print_success "Homebrew installed!"
+  step "Installing Homebrew…"
+  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
+  export PATH="/usr/local/bin:$PATH"
+  print_success "Homebrew installed!"
 else
-	print_success_muted "Homebrew already installed. Skipping."
+  print_success_muted "Homebrew already installed. Skipping."
 fi
 
-if brew list | grep -Fq brew-cask; then
-	step "Uninstalling old Homebrew-Cask…"
-	brew uninstall --force brew-cask
-	print_success "Homebrew-Cask uninstalled!"
+if brew list --formula | grep -Fq brew-cask; then
+  step "Uninstalling old Homebrew-Cask…"
+  brew uninstall --force brew-cask
+  print_success "Homebrew-Cask uninstalled!"
 fi
 
 ###############################################################################
 # INSTALL: brews
 ###############################################################################
 if [ -e $cwd/swag/brews ]; then
-	chapter "Installing Homebrew formulae…"
+  chapter "Installing Homebrew formulae…"
 
-	for brew in $(<$cwd/swag/brews); do
-		install_brews $brew
-	done
+  for brew in $(<$cwd/swag/brews); do
+  install_brews $brew
+  done
 fi
 
 ###############################################################################
@@ -155,11 +143,11 @@ brew update
 # INSTALL: casks
 ###############################################################################
 if [ -e $cwd/swag/casks ]; then
-	chapter "Installing apps via Homebrew…"
+  chapter "Installing apps via Homebrew…"
 
-	for cask in $(<$cwd/swag/casks); do
-	    install_application_via_brew $cask
-	done
+  for cask in $(<$cwd/swag/casks); do
+  install_application_via_brew $cask
+  done
 fi
 
 ###############################################################################
@@ -167,25 +155,21 @@ fi
 ###############################################################################
 chapter "Installing apps from App Store…"
 if [ -x mas ]; then
-
-	print_warning "Please install mas-cli first: brew mas. Skipping."
-
-	else
-
-	if [ -e $cwd/swag/apps ]; then
-		if mas_setup; then
-			# Workaround for associative array in Bash 3
-			# https://stackoverflow.com/questions/6047648/bash-4-associative-arrays-error-declare-a-invalid-option
-			for app in $(<$cwd/swag/apps); do
-				KEY="${app%%::*}"
-				VALUE="${app##*::}"
-				install_application_via_app_store $KEY $VALUE
-			done
-		else
-			print_warning "Please signin to App Store first. Skipping."
-		fi
-	fi
-
+  print_warning "Please install mas-cli first: brew mas. Skipping."
+else
+  if [ -e $cwd/swag/apps ]; then
+  if mas_setup; then
+  # Workaround for associative array in Bash 3
+  # https://stackoverflow.com/questions/6047648/bash-4-associative-arrays-error-declare-a-invalid-option
+  for app in $(<$cwd/swag/apps); do
+    KEY="${app%%::*}"
+    VALUE="${app##*::}"
+    install_application_via_app_store $KEY $VALUE
+    done
+  else
+    print_warning "Please signin to App Store first. Skipping."
+  fi
+  fi
 fi
 
 ###############################################################################
@@ -198,28 +182,27 @@ brew cleanup 2> /dev/null
 # INSTALL: npm packages
 ###############################################################################
 if [ -e $cwd/swag/npm ]; then
-	chapter "Installing npm packages…"
+  chapter "Installing npm packages…"
 
-	for pkg in $(<$cwd/swag/npm); do
-		KEY="${pkg%%::*}"
-		VALUE="${pkg##*::}"
-		install_npm_packages $KEY $VALUE
-	done
+  for pkg in $(<$cwd/swag/npm); do
+  KEY="${pkg%%::*}"
+  VALUE="${pkg##*::}"
+  install_npm_packages $KEY $VALUE
+  done
 fi
-
 
 ###############################################################################
 # OPTIONAL: Customizations
 ###############################################################################
 chapter "Adding hot sauce…"
-if [ -f $(<$cwd/swag/hot-sauce) ]; then
-	if ask "Do you want to add hot sauce?" Y; then
-		. $(<$cwd/swag/hot-sauce); printf "\n  You got hot sauce in your bag. 🔥 ${bold}Swag.${normal}\n";
-	else
-		print_success_muted "Hot sauce declined. Skipped.";
-	fi
+if [ -f "$cwd/swag/customizations" ]; then
+  if ask "Do you want to add hot sauce?" Y; then
+  . $cwd/swag/customizations; printf "\n  You got hot sauce in your bag. 🔥 ${bold}Swag.${normal}\n";
+  else
+  print_success_muted "Hot sauce declined. Skipped.";
+  fi
 else
-	print_warning "No ~/.hot-sauce found. Skipping."
+  print_warning "No $cwd/swag/customizations found. Skipping."
 fi
 
 ###############################################################################
